name: Compose Docker Cloud Backend Project

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: kaycccc/solace-backend:latest
      
      - name: Run Docker Compose
        run: |
          docker compose -f server/compose.production.yaml up --build -d
        env:
          MySQLPassword: ${{ secrets.MySQLPassword }}
          PortServer: ${{ secrets.PortServer }}
          PortDatabase: ${{ secrets.PortDatabase }}
          JwtKey: ${{ secrets.JwtKey }}
          JwtRefreshKey: ${{ secrets.JwtRefreshKey }}
          MailServer: ${{ secrets.MailServer }}
          MailPort: ${{ secrets.MailPort }}
          MailSenderName: ${{ secrets.MailSenderName }}
          MailSenderEmail: ${{ secrets.MailSenderEmail }}
          MailUserName: ${{ secrets.MailUserName }}
          MailPassword: ${{ secrets.MailPassword }}
          CloundName: ${{ secrets.CloundName }}
          CloundKey: ${{ secrets.CloundKey }}
          CloundSecret: ${{ secrets.CloundSecret }}
          ZaloPayAppId: ${{ secrets.ZaloPayAppId }}
          ZaloPayKey1: ${{ secrets.ZaloPayKey1 }}
          ZaloPayKey2: ${{ secrets.ZaloPayKey2 }}
          PayOSClientId: ${{ secrets.PayOSClientId }}
          PayOSApiKey: ${{ secrets.PayOSApiKey }}
          PayOSChecksumKey: ${{ secrets.PayOSChecksumKey }}
          PayOSDomain: ${{ secrets.PayOSDomain }}
          BotChatApiKey: ${{ secrets.BotChatApiKey }}
          AISkinAnalyzeUrl: ${{ secrets.AISkinAnalyzeUrl }}
          AISkinAnalyzeApiKey: ${{ secrets.AISkinAnalyzeApiKey }}
          ElasticSettingsBaseUrl: ${{ secrets.ElasticSettingsBaseUrl }}
          ElasticSettingsDefaultIndex: ${{ secrets.ElasticSettingsDefaultIndex }}
          ElasticSettingsFinger: ${{ secrets.ElasticSettingsFinger }}
          ElasticSettingsPassword: ${{ secrets.ElasticSettingsPassword }}
          MongoDbSettingConnectionString: ${{ secrets.MongoDbSettingConnectionString }}
          MongoDbSettingDatabaseName: ${{ secrets.MongoDbSettingDatabaseName }}
          RedisSettingConnectionString: ${{ secrets.RedisSettingConnectionString }}
